### ISSUE TITLE
OpenVPN 2.4 Debian 9.2.1

### ISSUE THREAD

**Issue by fuddel18** [angristan/openvpn-install#126]
Hello,
I have just installed Debian 9.2.1 on a virtual machine to test the OpenVPN 2.4 script.
When I create the key, I get an error message.

> Note:
>
> using Easy-RSA configuration from: ./vars
>
>init-pki complete; you may now create a CA or requests.
>Your newly created PKI dir is: /etc/openvpn/easy-rsa/pki
>
>Generating an EC private key
>writing new private key to '/etc/openvpn/easy-rsa/pki/private/ca.key.heeiw2dVYa'
>-----
>
>Note: using Easy-RSA configuration from: ./vars
>Generating an EC private key
>writing new private key to '/etc/openvpn/easy-rsa/pki/private/server.key.o8vDTkXU0B'
>-----
>rand: Use -help for summary.
>./easyrsa: 644: ./easyrsa: [[: not found
>Using configuration from ./openssl-1.0.cnf
>Can't open /etc/openvpn/easy-rsa/pki/index.txt.attr for reading, No such file or directory
>3072723264:error:02001002:system library:fopen:No such file or directory:../crypto
>/bio/bss_file.c:74:fopen('/etc/openvpn/easy-rsa/pki/index.txt.attr','r')
>3072723264:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:81:
>Check that the request matches the signature
>Signature ok
>The Subject's Distinguished Name is as follows
>commonName            :ASN.1 12:'server'
>Certificate is to be certified until Nov 14 16:18:40 2027 GMT (3650 days)
>
>Write out database with 1 new entries
>Data Base Updated
>
>Note: using Easy-RSA configuration from: ./vars
>Generating an EC private key
>writing new private key to '/etc/openvpn/easy-rsa/pki/private/client-test-2-4.key.CvrzBlvdV4'
>-----
>rand: Use -help for summary.
>./easyrsa: 644: ./easyrsa: [[: not found
>Using configuration from ./openssl-1.0.cnf
>Check that the request matches the signature
>Signature ok
>The Subject's Distinguished Name is as follows
>commonName            :ASN.1 12:'client-test-2-4'
>Certificate is to be certified until Nov 14 16:18:40 2027 GMT (3650 days)
>
>Write out database with 1 new entries
>Data Base Updated
>
>Note: using Easy-RSA configuration from: ./vars
>Using configuration from ./openssl-1.0.cnf
>
>An updated CRL has been created.
>CRL file: /etc/openvpn/easy-rsa/pki/crl.pem
>
>225
>Created symlink /etc/systemd/system/multi-user.target.wants/openvpn-server@openvpn.service → >/lib/systemd/system/openvpn-server@.service.
>
>Looks like your server is behind a NAT!
>
>If your server is NATed (e.g. LowEndSpirit, Scaleway, or behind a router),
>then I need to know the address that can be used to access it from outside.
>If that's not the case, just ignore this and leave the next field blank
>External IP or domain name: 

Can someone help me there?

Many Thanks.

**Comment by angristan** [comment]
Hi, how did you get the script?

**Comment by fuddel18** [comment]
I got the script from the drop down menu OpenVPn 2.4 Update and clicked on RAW.

[https://raw.githubusercontent.com/Angristan/OpenVPN-install/openvpn-2.4-update/openvpn-install.sh](url)

**Comment by angristan** [comment]
Ok. have you finished the installation and tested the config file?

**Comment by fuddel18** [comment]
Yes, I tested it. Unfortunately I could not establish a connection. Did it work for you?

**Comment by angristan** [comment]
Yes, what provider do you use?

**Comment by angristan** [comment]
I just pushed a commit, you may try again

**Comment by fuddel18** [comment]
First of all thanks for your effort and help.

I set up the virtual machine in my local network before I set it up on a server on the Internet.
I reset the virtual machine and again tested an updated script. Unfortunately, I still get the same error message from before and therefore no connection. VPN Client is a Samsung S7, Android 7.0, OpenVPN Client 1.1.24 (Build92)

**Comment by angristan** [comment]
The error message during the installation has no impact. This is very likely your network config.
When connecting, do you have an error message?

**Comment by fuddel18** [comment]
No, I do not get an error message.
On the server is also not the minimum installation without a firewall.

**Comment by angristan** [comment]
That's probably because your client can't reach your server due to your network config :(

**Comment by fuddel18** [comment]
When I connect to a OpenVPN server with a Windows 10 PC, a connection is established. Not with the smartphone.

Will the bug still be fixed which I pushed at the top?

**Comment by angristan** [comment]
That's strange, are they connected to the same network?

One of them will be fixed by easy-rsa, yes, but they don't have any impact on the installation.

**Comment by fuddel18** [comment]
Yes, all devices are in the same network. The PC is connected with network cable and the smartphone is connected via WLAN. But they are not filters or rules.

Currently I am working with your other script. OpenVPN 2.3.x works wonderfully.

**Comment by angristan** [comment]
When you tested the current, 2.3 script, was this PR merged? https://github.com/Angristan/OpenVPN-install/commit/f47fc795d5e2d53f74431aadc58ef9de5784103a

**Comment by fuddel18** [comment]
It was before the merger.

**Comment by angristan** [comment]
All right, then if you happen to retry the master script, let me know the results as it may be related to that PR

**Comment by fuddel18** [comment]
Sure, that's not a problem I repeat the Master Script.
When running the script again, there were no errors.
The connection with the equal PC and Smartphone works properly.
To setup:
It is the same Viruelle machine where the OpenVPN Script 2.4 has been executed. Even the network is the same and nothing has changed.

**Comment by angristan** [comment]
So it works with the master script before and after the PR, but the 2.4 one don't?

**Comment by fuddel18** [comment]
Yes, it works with the master script.

Unfortunately not with the Openvpn 2.4 script.

**Comment by Quintenps** [comment]
I'm having the same issue "./easyrsa: 644: ./easyrsa: [[: not found". Ubuntu 16.04 & 17.04 (server) :/

**Comment by angristan** [comment]
@Quintenps this is not an issue and it's not related, don't worry :) https://github.com/Angristan/OpenVPN-install/issues/101#issuecomment-330149831

**Comment by emilio1625** [comment]
I'm having the same issue on Fedora 27 and in Fedberry 27 (Fedora 27 armhfp with custom kernel), i cannot establish the connection, i get this error messages in the server
```
openvpn[525]: tls-crypt unwrap error: packet too short
openvpn[525]: TLS Error: tls-crypt unwrapping failed from [AF_INET]xxx.xxx.xxx.xxx:xxxxx
```
disabling the following lines in the sever.conf seem to fix it, but if i understand right this disables the
control channel encryption
`tls-crypt tls-crypt.key 0`

**Comment by randshell** [comment]
Yes, it's a client problem.

Not sure if you still can't connect from Android with that app, but try Openvpn for Androidf by Arne Schwabe. It supports the latest v2.4 features and it should work.

**Comment by angristan** [comment]
Closing since this is not a "stable" branch
